In [1]:
import numpy as np

In [2]:
myList = [1,2,3]

In [3]:
type(myList)

list

In [4]:
np.array(myList)

array([1, 2, 3])

In [5]:
myList

[1, 2, 3]

In [6]:
myArray = np.array(myList)

In [7]:
myArray

array([1, 2, 3])

In [8]:
type(myArray)

numpy.ndarray

In [10]:
# numpy.ndarray means that it is converted to n-dimensional array

In [11]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
myMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

np.arange(0,101,2)

In [17]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [2]:
import numpy as np

In [ ]:
np.arange()