In [4]:
import numpy as np

In [5]:
myList = [1,2,3]

In [6]:
type(myList)

list

In [7]:
np.array(myList)

array([1, 2, 3])

In [8]:
myList

[1, 2, 3]

In [9]:
myArray = np.array(myList)

In [10]:
myArray

array([1, 2, 3])

In [11]:
type(myArray)

numpy.ndarray

In [12]:
# numpy.ndarray means that it is converted to n-dimensional array

In [13]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [14]:
myMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

np.arange(0,101,2)

In [18]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
arr = np.arange(0,11)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[1:5]

array([1, 2, 3, 4])

In [28]:
arr [5:9]

array([5, 6, 7, 8])

In [29]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
# sliced arr

In [31]:
arr[0:5] = 100

In [32]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [34]:
arr = np.arange(0,11)

In [35]:
sliceofarray = arr[0:5]

In [36]:
sliceofarray

array([0, 1, 2, 3, 4])

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
sliceofarray[0:] = 99

In [39]:
sliceofarray

array([99, 99, 99, 99, 99])

In [41]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [42]:
# overwriting values in the variable sliceofarray will also change values in the main NP array var, arr

In [43]:
# we have only changed the values in sliceofarray but it will also reflect in main array

In [44]:
# this is called broadcasting

In [46]:
# we have not copied arr into sliceofarray; rather, we have just gotten a piece of arr and passed it to sliceofarray.

In [47]:
# now we will copy the main array to a new variable arr_copy

In [48]:
arr_copy = arr.copy()

In [49]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [50]:
arr_copy[:] = 100 #only colon means from start to end

In [51]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [52]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [53]:
# as you can see the original array is same

In [55]:
arr_2d = np.array([[5,10,15],[2,4,6],[1,2,3]]) # new 2d array

In [56]:
arr_2d

array([[ 5, 10, 15],
       [ 2,  4,  6],
       [ 1,  2,  3]])

In [57]:
# the array is a square, but we must check

In [59]:
arr_2d.shape

(3, 3)

In [60]:
# 3 rows, 3 columns

In [61]:
arr_2d[0]

array([ 5, 10, 15])

In [62]:
# as you can see it shows only the first row

In [63]:
arr_2d[2]

array([1, 2, 3])

In [64]:
# now it prints third line

In [68]:
arr_2d[1,1]

4

In [69]:
# now it prints the 1,1 in the array (2,2 to us but 1,1 to machine)

In [75]:
arr_2d[1][1]

4

In [76]:
# same output

In [79]:
arr_2d[0:2]

array([[ 5, 10, 15],
       [ 2,  4,  6]])

In [80]:
# now it prints the first two rows

In [85]:
arr_2d[:2,1:]

array([[10, 15],
       [ 4,  6]])

In [86]:
# now it prints the last two elements of the first two rows

In [92]:
arr = np.arange(1,10)

In [93]:
#reset main array arr

In [94]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [96]:
# displays which elements greater than 5

In [97]:
bool_arr = arr > 5

In [98]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True])

In [99]:
# putting this into a variable

In [102]:
arr[bool_arr]

array([6, 7, 8, 9])

In [103]:
# this shows only the values that match the statement arr > 5

In [104]:
arr[arr>5]

array([6, 7, 8, 9])

In [105]:
# second method