In [4]:
import numpy as np

In [5]:
myList = [1,2,3]

In [6]:
type(myList)

list

In [7]:
np.array(myList)

array([1, 2, 3])

In [8]:
myList

[1, 2, 3]

In [9]:
myArray = np.array(myList)

In [10]:
myArray

array([1, 2, 3])

In [11]:
type(myArray)

numpy.ndarray

In [12]:
# numpy.ndarray means that it is converted to n-dimensional array

In [13]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [14]:
myMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

np.arange(0,101,2)

In [18]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
arr = np.arange(0,11)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[1:5]

array([1, 2, 3, 4])

In [28]:
arr [5:9]

array([5, 6, 7, 8])

In [29]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
# sliced arr