In [1]:
import numpy as np

In [2]:
myList = [1,2,3]

In [3]:
type(myList)

list

In [4]:
np.array(myList)

array([1, 2, 3])

In [5]:
myList

[1, 2, 3]

In [6]:
myArray = np.array(myList)

In [7]:
myArray

array([1, 2, 3])

In [8]:
type(myArray)

numpy.ndarray

In [9]:
# numpy.ndarray means that it is converted to n-dimensional array

In [10]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
myMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

np.arange(0,101,2)

In [15]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
arr = np.arange(0,11)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr[1:5]

array([1, 2, 3, 4])

In [23]:
arr [5:9]

array([5, 6, 7, 8])

In [24]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [25]:
# sliced arr

In [26]:
arr[0:5] = 100

In [27]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [28]:
arr = np.arange(0,11)

In [29]:
sliceofarray = arr[0:5]

In [30]:
sliceofarray

array([0, 1, 2, 3, 4])

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
sliceofarray[0:] = 99

In [33]:
sliceofarray

array([99, 99, 99, 99, 99])

In [34]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [35]:
# overwriting values in the variable sliceofarray will also change values in the main NP array var, arr

In [36]:
# we have only changed the values in sliceofarray but it will also reflect in main array

In [37]:
# this is called broadcasting

In [38]:
# we have not copied arr into sliceofarray; rather, we have just gotten a piece of arr and passed it to sliceofarray.

In [39]:
# now we will copy the main array to a new variable arr_copy

In [40]:
arr_copy = arr.copy()

In [41]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [42]:
arr_copy[:] = 100 #only colon means from start to end

In [43]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [44]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [45]:
# as you can see the original array is same

In [46]:
arr_2d = np.array([[5,10,15],[2,4,6],[1,2,3]]) # new 2d array

In [47]:
arr_2d

array([[ 5, 10, 15],
       [ 2,  4,  6],
       [ 1,  2,  3]])

In [48]:
# the array is a square, but we must check

In [49]:
arr_2d.shape

(3, 3)

In [50]:
# 3 rows, 3 columns

In [51]:
arr_2d[0]

array([ 5, 10, 15])

In [52]:
# as you can see it shows only the first row

In [53]:
arr_2d[2]

array([1, 2, 3])

In [54]:
# now it prints third line

In [55]:
arr_2d[1,1]

4

In [56]:
# now it prints the 1,1 in the array (2,2 to us but 1,1 to machine)

In [57]:
arr_2d[1][1]

4

In [58]:
# same output

In [59]:
arr_2d[0:2]

array([[ 5, 10, 15],
       [ 2,  4,  6]])

In [60]:
# now it prints the first two rows

In [61]:
arr_2d[:2,1:]

array([[10, 15],
       [ 4,  6]])

In [62]:
# now it prints the last two elements of the first two rows

In [63]:
arr = np.arange(1,10)

In [64]:
#reset main array arr

In [65]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [67]:
# displays which elements greater than 5

In [68]:
bool_arr = arr > 5

In [69]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True])

In [70]:
# putting this into a variable

In [71]:
arr[bool_arr]

array([6, 7, 8, 9])

In [72]:
# this shows only the values that match the statement arr > 5

In [73]:
arr[arr>5]

array([6, 7, 8, 9])

In [74]:
# second method

In [75]:
# both methods work to display the same thing