In [1]:
# 1. Import NumPy as np

In [2]:
import numpy as np

In [3]:
# 2. Create an array of 10 zeros

In [4]:
zerosarr = np.arange(0,10)
zerosarr[0:] = 0

In [5]:
zerosarr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# 3. Create an array of 10 ones

In [7]:
onesarr = np.arange(0,10)
onesarr[0:] = 0

In [8]:
onesarr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# 4. Create an array of 10 fives

In [10]:
fivesarr = np.arange(0,10)
fivesarr[0:] = 5

In [11]:
fivesarr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [12]:
# 5. Create an array of the integers from 10 to 50

In [13]:
tentofiftyarrbase = np.arange(0,41)
tentofiftyarr = tentofiftyarrbase + 10

In [14]:
tentofiftyarr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [15]:
# 6. Create an array of all the even integers from 10 to 50

In [16]:
modtentofiftyarr = tentofiftyarr % 2
boolmodtentofiftyarr = modtentofiftyarr <= 0

In [17]:
tentofiftyarr[boolmodtentofiftyarr]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [18]:
# 7. Create a 3x3 matrix with values ranging from 0 to 8.

In [19]:
zerotoeightmatrix = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [20]:
zerotoeightmatrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
# 8. Create a 3x3 identity matrix

In [22]:
identitymatrix = np.identity(3)

In [23]:
identitymatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# 9. Use NumPy to generate a random number between 0 and 1

In [25]:
randnumzerotoone = np.random.normal(0,1,1)

In [26]:
randnumzerotoone

array([-0.29256665])

In [27]:
# 10. Use NumPy to genereate an array of 25 random numbers sampled from a standard normal distribution

In [28]:
randnumtwentyfiverandoms = np.random.normal(0,1,25)

In [29]:
randnumtwentyfiverandoms

array([-2.38604978e-01,  1.50561707e+00, -7.02027538e-01, -1.66358773e-03,
       -6.17180405e-03,  7.39762200e-01, -6.35359798e-01,  3.40162747e-01,
        8.58884250e-01, -2.60952285e+00, -1.01830770e+00, -1.36446724e+00,
        1.11529315e+00,  1.25154234e+00,  8.02440026e-01,  3.74267255e-01,
       -7.69316021e-01,  8.78565998e-01,  3.09489588e+00, -1.45292357e+00,
        8.09209378e-01, -1.19791062e+00,  2.48803223e-01,  1.12951965e+00,
        2.00317882e+00])

In [30]:
# 11. Create a 10x10 matrix that goes from 0.01 to 1

In [32]:
arr = np.arange(0.01,1.00)
arr

array([0.01])

In [ ]:
# 12. 