# Numpy Basic Exercises (Redo)

This time, I'm doing it with more knowledge of Python in general, and aim to make the code more optimized than last time.

#### 1. Import NumPy as np

In [1]:
import numpy as np

#### 2. Create an array of 10 zeros

In [2]:
zerosArr = np.zeros(10)
zerosArr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [3]:
onesArr = np.ones(10)
onesArr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [4]:
fivesArr = np.arange(0,10)
fivesArr[0:] = 5
fivesArr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### 5. Create an array of the integers from 10 to 50

In [5]:
tenToFiftyArr = np.arange(10,51)
tenToFiftyArr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Create an array of all the even integers from 10 to 50.

In [6]:
tenToFiftyEvenArr = tenToFiftyArr[(tenToFiftyArr % 2) <= 0]
tenToFiftyEvenArr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Create a 3x3 identity matrix

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Use NumPy to generate a random number between 0 and 1

In [9]:
# practically almost impossible to have an output above one, but statistically possible
randZeroToOne = abs(np.random.normal(0,1,1))
if randZeroToOne > 1:
    randZeroToOne = randZeroToOne - 1
randZeroToOne

array([0.73124388])

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution.

In [10]:
np.random.normal(0,1,25)

array([-0.62006574, -1.49982539,  0.819471  , -0.50099458, -0.36748172,
       -0.12692143, -0.02299827, -0.07363728, -0.90970883,  0.3555848 ,
        2.10331206,  0.42029094,  0.95046498,  1.01068074,  0.48818723,
       -0.98963229, -1.27730427,  1.21170737, -0.2707955 ,  0.19852693,
        0.27704557, -1.10164207, -0.43535481,  1.67444647, -0.97361109])

#### 11. Create a 10x10 matrix that goes from 0.01 to 1

In [11]:
np.arange(1,101)/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### 12. Create an array of 20 linearly spaced points between 0 and 1.

In [12]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection

Now you will be given a starting matrix and asked to replicate the matrix based on the image. You can see the image in the "All Exercises" subdirectory at `My-AI/NumPy Basics/NumPy Basic Exercises/All Exercises/Task 12-13`

#### Run the code below, it's the starting matrix

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code that reproduces the output shown below.