#### 1. Import NumPy as np

In [1]:
import numpy as np

#### 2. Create an array of 10 zeros

In [2]:
zerosArr = np.zeros(10)
zerosArr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [3]:
onesArr = np.ones(10)
onesArr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [4]:
fivesArr = np.arange(0,10)
fivesArr[0:] = 5
fivesArr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])