In [1]:
# 1. Import NumPy as np

In [2]:
import numpy as np

In [3]:
# 2. Create an array of 10 zeros

In [4]:
zerosarr = np.arange(0,10)
zerosarr[0:] = 0

In [5]:
zerosarr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# 3. Create an array of 10 ones

In [7]:
onesarr = np.arange(0,10)
onesarr[0:] = 0

In [8]:
onesarr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# 4. Create an array of 10 fives

In [10]:
fivesarr = np.arange(0,10)
fivesarr[0:] = 5

In [11]:
fivesarr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [12]:
# 5. Create an array of the integers from 10 to 50

In [13]:
tentofiftyarrbase = np.arange(0,41)
tentofiftyarr = tentofiftyarrbase + 10

In [14]:
tentofiftyarr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [15]:
# 6. Create an array of all the even integers from 10 to 50

In [16]:
modtentofiftyarr = tentofiftyarr % 2
boolmodtentofiftyarr = modtentofiftyarr <= 0

In [17]:
tentofiftyarr[boolmodtentofiftyarr]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [18]:
# 7. Create a 3x3 matrix with values ranging from 0 to 8.

In [19]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
# 8. Create a 3x3 identity matrix

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# 9. Use NumPy to generate a random number between 0 and 1

In [23]:
np.random.normal(0,1,1)

array([0.82915885])

In [24]:
# 10. Use NumPy to genereate an array of 25 random numbers sampled from a standard normal distribution

In [25]:
np.random.normal(0,1,25)

array([ 1.69035964,  1.72231751,  0.6755616 ,  0.48767878,  1.17089727,
        1.5386021 , -0.07305095, -1.25677276,  0.84956853, -0.41079457,
       -0.52599406, -0.10947643, -0.73281755,  0.78043984,  1.11595434,
        0.40143647,  1.15950005,  1.34987385,  1.25833908,  1.10234517,
        0.26766619,  0.59208527,  1.43197373, -0.24440521,  1.02208283])

In [26]:
# 11. Create a 10x10 matrix that goes from 0.01 to 1

In [27]:
np.arange(1,101)/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [28]:
# 12. Create an array of 20 linearly-spaced points between 0 to 1.

In [29]:
np.arange(1,21)/20

array([0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55,
       0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

# NumPy Indexing and Selection

Now you will be given a starting matrix and asked to replicate the matrix based on the image. You can see the image in the "All Exercises" subdirectory at `My-AI/NumPy Basics/NumPy Basic Exercises/All Exercises/Task 12-13`

In [30]:
# Run this code, this is our starting matrix.

In [31]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
#