#### 1. Import NumPy as np

In [1]:
import numpy as np

#### 2. Create an array of 10 zeros

In [2]:
zerosarr = np.zeros(10)
zerosarr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [3]:
onesarr = np.ones(10)
onesarr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [4]:
fivesarr = np.arange(0,10)
fivesarr[0:] = 5
fivesarr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])