In [1]:
# 1. Import NumPy as np

In [2]:
import numpy as np

In [3]:
# 2. Create an array of ten zeros

In [4]:
zerosarr = np.arange(0,10)
zerosarr[0:] = 0

In [5]:
zerosarr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# 3. Create an array of ten ones

In [7]:
onesarr = np.arange(0,10)
onesarr[0:] = 0

In [8]:
onesarr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# 4. Create an array of ten fives

In [10]:
fivesarr = np.arange(0,10)
fivesarr[0:] = 5

In [11]:
fivesarr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])