# Numpy Basic Exercises (Redo)

This time, I'm doing it with more knowledge of Python in general, and aim to make the code more optimized than last time.

#### 1. Import NumPy as np

In [1]:
import numpy as np

#### 2. Create an array of 10 zeros

In [2]:
zerosArr = np.zeros(10)
zerosArr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [3]:
onesArr = np.ones(10)
onesArr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [4]:
fivesArr = np.arange(0,10)
fivesArr[0:] = 5
fivesArr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### 5. Create an array of the integers from 10 to 50

In [5]:
tenToFiftyArr = np.arange(10,51)
tenToFiftyArr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Create an array of all the even integers from 10 to 50.

In [6]:
tenToFiftyEvenArr = tenToFiftyArr[(tenToFiftyArr % 2) <= 0]
tenToFiftyEvenArr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Create a 3x3 identity matrix

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Use NumPy to generate a random number between 0 and 1

In [9]:
randZeroToOne = abs(np.random.normal(0,1,1))
if randZeroToOne > 1:
    randZeroToOne = randZeroToOne - 1
randZeroToOne

array([0.1172125])

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution.

In [10]:
np.random.normal(0,1,25)

array([-0.51121612, -0.58926685,  0.5764447 ,  0.07704401,  0.01469957,
        1.37939615, -0.05613152, -1.05898419,  0.23150171,  0.08222907,
       -1.6508911 ,  1.37894241, -0.13560575, -2.07705434, -0.53667187,
        0.43256406, -0.69939873,  0.70548476,  1.61910299,  0.74747677,
       -2.1479014 ,  0.03746753,  0.36773192, -0.16598702,  1.30019511])

#### 11. Create a 10x10 matrix that goes from 0.01 to 1