In [1]:
# 1. Import NumPy as np

In [2]:
import numpy as np

In [3]:
# 2. Create an array of 10 zeros

In [4]:
zerosarr = np.arange(0,10)
zerosarr[0:] = 0

In [5]:
zerosarr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# 3. Create an array of 10 ones

In [7]:
onesarr = np.arange(0,10)
onesarr[0:] = 0

In [8]:
onesarr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# 4. Create an array of 10 fives

In [10]:
fivesarr = np.arange(0,10)
fivesarr[0:] = 5

In [11]:
fivesarr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [12]:
# 5. Create an array of the integers from 10 to 50

In [13]:
tentofiftyarrbase = np.arange(0,41)
tentofiftyarr = tentofiftyarrbase + 10

In [14]:
tentofiftyarr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [15]:
# 6. Create an array of all the even integers from 10 to 50

In [16]:
modtentofiftyarr = tentofiftyarr % 2
boolmodtentofiftyarr = modtentofiftyarr <= 0

In [17]:
tentofiftyarr[boolmodtentofiftyarr]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [18]:
# 7. Create a 3x3 matrix with values ranging from 0 to 8.

In [19]:
zerotoeightmatrix = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [20]:
zerotoeightmatrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
# 8. Create a 3x3 identity matrix

In [22]:
identitymatrix = np.identity(3)

In [23]:
identitymatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# 9. Use NumPy to generate a random number between 0 and 1

In [25]:
randnumzerotoone = np.random.normal(0,1,1)

In [26]:
randnumzerotoone

array([-0.26935177])

In [27]:
# 10. Use NumPy to genereate an array of 25 random numbers sampled from a standard normal distribution

In [28]:
randnumtwentyfiverandoms = np.random.normal(0,1,25)

In [29]:
randnumtwentyfiverandoms

array([ 0.64656064, -1.85043402, -0.4706135 , -0.71470959, -1.0973206 ,
       -0.24103146,  1.4455039 , -0.94817222, -0.89231691,  0.78406634,
        0.28322603, -0.91369303, -0.37914609, -0.66904266, -0.56079116,
        0.16018237,  0.0451917 , -0.61990605, -0.10910722, -0.2150999 ,
        1.13842914,  0.5204015 , -0.76363752, -0.63272178, -0.01419287])

In [30]:
# 11. Create a 10x10 matrix that goes from 0.01 to 1